import type {
  Recommendation,
  DataMode,
} from '../../domain/types';

const DEMO_MODE: DataMode = 'demo';

export const demoRecommendations: Recommendation[] = [
  {
    id: 'rec-demo-001',
    businessId: 'demo-biz-001',
    title: 'Responder a las resenas de tus clientes',
    summary: 'Responder a las resenas, positivas y negativas, ayuda a cuidar tu reputacion online.',
    explanation: 'Los clientes valoran que un negocio responda. Responder demuestra actividad y confianza.',
    reason: 'Buena practica general: las resenas sin respuesta suelen reducir la confianza de nuevos clientes.',
    source: 'Recomendacion general',
    sourceType: 'google_business',
    sourceUpdatedAt: null,
    confidence: 'demo',
    impact: 'high',
    estimatedTimeMinutes: 7,
    status: 'new',
    actionType: 'respond_reviews',
    createdAt: '2026-07-25T08:00:00Z',
    dataMode: DEMO_MODE,
  },
  {
    id: 'rec-demo-002',
    businessId: 'demo-biz-001',
    title: 'Publicar una actualizacion semanal',
    summary: 'Publicar con regularidad mantiene tu perfil activo ante Google y tus clientes.',
    explanation: 'Los perfiles con publicaciones recientes reciben mas clics. Un post semanal mantiene tu perfil activo.',
    reason: 'Buena practica general: un perfil sin publicaciones recientes puede parecer inactivo.',
    source: 'Recomendacion general',
    sourceType: 'google_business',
    sourceUpdatedAt: null,
    confidence: 'demo',
    impact: 'medium',
    estimatedTimeMinutes: 12,
    status: 'new',
    actionType: 'publish_post',
    createdAt: '2026-07-25T08:00:00Z',
    dataMode: DEMO_MODE,
  },
  {
    id: 'rec-demo-003',
    businessId: 'demo-biz-001',
    title: 'Revisar la descripcion del negocio',
    summary: 'Una descripcion con palabras clave locales puede mejorar tu posicionamiento.',
    explanation: 'Una descripcion con tu ciudad, barrio y servicios especificos ayuda a que aparezcas en busquedas relevantes.',
    reason: 'Buena practica general: mencionar tu ubicacion y tus servicios diferenciadores en la descripcion.',
    source: 'Recomendacion general',
    sourceType: 'website',
    sourceUpdatedAt: null,
    confidence: 'demo',
    impact: 'medium',
    estimatedTimeMinutes: 20,
    status: 'new',
    actionType: 'update_description',
    createdAt: '2026-07-25T08:00:00Z',
    dataMode: DEMO_MODE,
  },
  {
    id: 'rec-demo-004',
    businessId: 'demo-biz-001',
    title: 'Subir fotos actuales del negocio',
    summary: 'Las fotos actualizadas generan confianza visual para nuevos clientes.',
    explanation: 'Los clientes quieren ver el estado real del negocio antes de visitarlo.',
    reason: 'Buena practica general: renovar las fotos cada pocas semanas.',
    source: 'Recomendacion general',
    sourceType: 'google_business',
    sourceUpdatedAt: null,
    confidence: 'demo',
    impact: 'low',
    estimatedTimeMinutes: 10,
    status: 'new',
    actionType: 'add_photos',
    createdAt: '2026-07-25T08:00:00Z',
    dataMode: DEMO_MODE,
  },
  {
    id: 'rec-demo-005',
    businessId: 'demo-biz-001',
    title: 'Verificar tu horario publicado',
    summary: 'Comprueba que el horario publicado coincide con tu horario real, sobre todo en cambios de temporada.',
    explanation: 'Un horario incorrecto frustra a clientes que llegan y encuentran cerrado.',
    reason: 'Buena practica general: revisar el horario en cada cambio de temporada o festivo.',
    source: 'Recomendacion general',
    sourceType: 'google_business',
    sourceUpdatedAt: null,
    confidence: 'demo',
    impact: 'low',
    estimatedTimeMinutes: 5,
    status: 'new',
    actionType: 'update_hours',
    createdAt: '2026-07-25T08:00:00Z',
    dataMode: DEMO_MODE,
  },
];
