import type { Lang } from '../../lib/i18n';

const COPY = {
  es: {
    daysLeft: (n: number) => (n === 1 ? 'Te queda 1 día de prueba gratuita' : `Te quedan ${n} días de prueba gratuita`),
    endsToday: 'Tu prueba termina hoy',
    ended: 'Tu prueba gratuita ha finalizado',
    endsOn: (d: string) => `Termina el ${d}`,
    endsAt: (d: string) => `Termina el ${d}. Después podrás seguir con una suscripción de 9,99 €/mes.`,
    subscribe: 'Activar suscripción',
    openingCheckout: 'Abriendo pago seguro...',
    manage: 'Gestionar suscripción',
    viewBilling: 'Ver facturación',
    upgradeTitle: 'Tu prueba gratuita ha terminado',
    upgradeBody: 'Tu negocio, tus acciones y tu progreso siguen guardados. Puedes continuar utilizando las funciones de LocalSEOHub con una suscripción de 9,99 €/mes.',
    canceledTitle: 'Tu suscripción ha finalizado',
    canceledBody: 'Tu negocio, tus acciones y tu progreso siguen guardados. Puedes reactivar LocalSEOHub cuando quieras por 9,99 €/mes.',
    pastDueTitle: 'No hemos podido cobrar tu último pago',
    pastDueBody: 'Actualiza tu método de pago para seguir usando LocalSEOHub sin interrupciones.',
    pendingTitle: 'Estamos confirmando tu pago',
    pendingBody: 'En cuanto el banco confirme el pago, tu suscripción se activará. Puede tardar unos minutos.',
    cancelingBody: (d: string) => `Tu suscripción se cancelará el ${d}. Hasta entonces mantienes el acceso completo.`,
    startTitle: 'Activa tu prueba gratuita de 7 días',
    startBody: 'Acceso completo a LocalSEOHub durante 7 días. Sin tarjeta y sin cobros automáticos: al terminar decides si quieres suscribirte.',
    startCta: 'Empezar prueba gratuita',
    starting: 'Activando...',
    startError: 'No hemos podido activar tu prueba. Inténtalo de nuevo.',
    paywallAction: 'Para iniciar o completar acciones necesitas una prueba activa o una suscripción. Tus acciones siguen aquí.',
    pageTitle: 'Facturación',
    pageSubtitle: 'Tu plan, tu prueba y tus pagos en un solo lugar.',
    plan: 'Plan LocalSEOHub',
    planDesc: 'Todas las funciones, un único precio. Cancela cuando quieras.',
    perMonth: '/mes',
    status: 'Estado',
    trialEnd: 'Fin de la prueba',
    nextBilling: 'Próximo cobro',
    accessUntil: 'Acceso hasta',
    paymentMethod: 'Método de pago',
    updatePayment: 'Actualizar método de pago',
    cancel: 'Cancelar suscripción',
    cancelConfirmTitle: '¿Cancelar tu suscripción?',
    cancelConfirmBody: (d: string) => `Mantendrás el acceso completo hasta el ${d}. Después no se te cobrará más y todos tus datos seguirán guardados.`,
    cancelConfirm: 'Sí, cancelar',
    keep: 'Mantener suscripción',
    resume: 'Reanudar suscripción',
    refresh: 'Actualizar estado',
    checkoutReturned: 'Estamos confirmando tu pago con Stripe. Tu acceso se activará en cuanto se confirme.',
    checkoutCanceled: 'No se ha realizado ningún cobro. Puedes activar tu suscripción cuando quieras.',
    secure: 'Pago seguro con Stripe. LocalSEOHub nunca ve los datos de tu tarjeta.',
    noCharge: 'Durante la prueba no se te cobrará nada.',
    subscribeDuringTrial: (d: string) => `Si te suscribes ahora, el primer cobro de 9,99 € se hará cuando termine tu prueba, el ${d}.`,
    errors: {
      already_subscribed: 'Ya tienes una suscripción. Gestiónala desde aquí.',
      no_subscription: 'No hemos encontrado una suscripción activa.',
      billing_unavailable: 'Los pagos no están disponibles en este momento. Inténtalo más tarde.',
      unauthorized: 'Tu sesión ha caducado. Vuelve a iniciar sesión.',
      billing_failed: 'Algo ha fallado. Inténtalo de nuevo en unos segundos.',
    },
    loadError: 'No hemos podido cargar tu estado de facturación.',
    retry: 'Reintentar',
    states: {
      TRIAL_NOT_STARTED: 'Prueba sin activar',
      TRIAL_ACTIVE: 'Prueba gratuita',
      TRIAL_EXPIRED: 'Prueba finalizada',
      SUBSCRIPTION_ACTIVE: 'Activa',
      SUBSCRIPTION_CANCELING: 'Cancelación programada',
      SUBSCRIPTION_PAST_DUE: 'Pago pendiente',
      SUBSCRIPTION_CANCELED: 'Cancelada',
      PAYMENT_PENDING: 'Confirmando pago',
    },
  },
  en: {
    daysLeft: (n: number) => (n === 1 ? 'You have 1 day left in your free trial' : `You have ${n} days left in your free trial`),
    endsToday: 'Your trial ends today',
    ended: 'Your free trial has ended',
    endsOn: (d: string) => `Ends on ${d}`,
    endsAt: (d: string) => `Ends on ${d}. After that you can continue with a €9.99/month subscription.`,
    subscribe: 'Activate subscription',
    openingCheckout: 'Opening secure checkout...',
    manage: 'Manage subscription',
    viewBilling: 'View billing',
    upgradeTitle: 'Your free trial has ended',
    upgradeBody: 'Your business, your actions and your progress are still saved. You can keep using LocalSEOHub features with a €9.99/month subscription.',
    canceledTitle: 'Your subscription has ended',
    canceledBody: 'Your business, your actions and your progress are still saved. You can reactivate LocalSEOHub any time for €9.99/month.',
    pastDueTitle: "We couldn't collect your last payment",
    pastDueBody: 'Update your payment method to keep using LocalSEOHub without interruption.',
    pendingTitle: "We're confirming your payment",
    pendingBody: 'As soon as your bank confirms the payment, your subscription will activate. This can take a few minutes.',
    cancelingBody: (d: string) => `Your subscription will be canceled on ${d}. Until then you keep full access.`,
    startTitle: 'Start your 7-day free trial',
    startBody: 'Full access to LocalSEOHub for 7 days. No card and no automatic charges: when it ends, you decide whether to subscribe.',
    startCta: 'Start free trial',
    starting: 'Activating...',
    startError: "We couldn't start your trial. Please try again.",
    paywallAction: 'To start or complete actions you need an active trial or subscription. Your actions are still here.',
    pageTitle: 'Billing',
    pageSubtitle: 'Your plan, trial and payments in one place.',
    plan: 'LocalSEOHub plan',
    planDesc: 'Every feature, one price. Cancel any time.',
    perMonth: '/month',
    status: 'Status',
    trialEnd: 'Trial ends',
    nextBilling: 'Next charge',
    accessUntil: 'Access until',
    paymentMethod: 'Payment method',
    updatePayment: 'Update payment method',
    cancel: 'Cancel subscription',
    cancelConfirmTitle: 'Cancel your subscription?',
    cancelConfirmBody: (d: string) => `You keep full access until ${d}. After that you won't be charged again and all your data stays saved.`,
    cancelConfirm: 'Yes, cancel',
    keep: 'Keep subscription',
    resume: 'Resume subscription',
    refresh: 'Refresh status',
    checkoutReturned: "We're confirming your payment with Stripe. Your access activates as soon as it's confirmed.",
    checkoutCanceled: 'No charge was made. You can activate your subscription whenever you like.',
    secure: 'Secure payment with Stripe. LocalSEOHub never sees your card details.',
    noCharge: "You won't be charged anything during the trial.",
    subscribeDuringTrial: (d: string) => `If you subscribe now, the first €9.99 charge happens when your trial ends, on ${d}.`,
    errors: {
      already_subscribed: 'You already have a subscription. Manage it here.',
      no_subscription: "We couldn't find an active subscription.",
      billing_unavailable: 'Payments are unavailable right now. Please try later.',
      unauthorized: 'Your session expired. Please sign in again.',
      billing_failed: 'Something went wrong. Please try again in a few seconds.',
    },
    loadError: "We couldn't load your billing status.",
    retry: 'Retry',
    states: {
      TRIAL_NOT_STARTED: 'Trial not started',
      TRIAL_ACTIVE: 'Free trial',
      TRIAL_EXPIRED: 'Trial ended',
      SUBSCRIPTION_ACTIVE: 'Active',
      SUBSCRIPTION_CANCELING: 'Cancellation scheduled',
      SUBSCRIPTION_PAST_DUE: 'Payment issue',
      SUBSCRIPTION_CANCELED: 'Canceled',
      PAYMENT_PENDING: 'Confirming payment',
    },
  },
};

export type BillingCopy = (typeof COPY)['es'];

export function billingCopy(lang: Lang): BillingCopy {
  return COPY[lang];
}
