import type { WeeklyContentErrorCode } from './model';

const ES = {
  title: 'Tu contenido de la semana',
  intro: 'Cada semana te ayudamos a preparar una publicación para dar visibilidad a tu negocio.',
  week: (from: string, to: string) => `Semana del ${from} al ${to}`,
  draft: 'Borrador · no publicado',
  prepare: 'Preparar mi contenido',
  preparing: 'Preparando tu contenido...',
  prepareNote: 'Usamos solo los datos de tu negocio. No inventamos precios, ofertas, horarios ni opiniones.',
  copy: 'Copiar', copied: 'Copiado', edit: 'Editar', another: 'Otra versión',
  remaining: (n: number) => (n === 1 ? 'queda 1' : `quedan ${n}`),
  save: 'Guardar cambios', saving: 'Guardando...', cancel: 'Cancelar',
  saved: 'Guardado', editedSaved: 'Editado por ti · guardado', copiedOnce: 'Copiado al portapapeles',
  unsaved: 'Cambios sin guardar',
  limitInfo: 'Has usado las 3 versiones de esta semana. Puedes seguir editando este texto.',
  replaceEdited: 'Tu texto editado se sustituirá por una versión nueva. ¿Continuar?',
  replaceYes: 'Sí, crear otra versión', replaceNo: 'No, mantener mi texto',
  chars: (n: number, max: number) => `${n}/${max}`,
  emptyEdit: 'El texto no puede quedar vacío.',
  tooLong: 'El texto es demasiado largo.',
  incompleteTitle: 'Completa tu negocio para preparar tu contenido',
  incompleteText: 'Necesitamos el nombre, la actividad, la ciudad y al menos un servicio. Así el texto habla de tu negocio de verdad y no es genérico.',
  incompleteCta: 'Completar mi negocio',
  lockedText: 'Preparar contenido está incluido en la prueba gratuita y en la suscripción.',
  loadError: 'No hemos podido cargar tu contenido de la semana.',
  retry: 'Reintentar',
  saveError: 'No hemos podido guardar tus cambios. Tu texto sigue aquí; inténtalo de nuevo.',
  conflict: 'Este contenido ha cambiado en otra ventana. Copia tu texto si quieres conservarlo y carga la última versión.',
  loadLatest: 'Cargar la última versión',
  copyError: 'No hemos podido copiar el texto. Selecciónalo y cópialo manualmente.',
  close: 'Cerrar',
  editLabel: 'Texto de tu publicación',
  errors: {
    profile_incomplete: 'Faltan datos de tu negocio para preparar un contenido fiel. Complétalos en Mi negocio.',
    limit_reached: 'Ya has usado las 3 versiones de esta semana. Puedes seguir editando el texto actual.',
    in_progress: 'Ya estamos preparando tu contenido en otra ventana. Espera unos segundos y vuelve a intentarlo.',
    ai_unavailable: 'El servicio de redacción no está disponible ahora mismo. No se ha gastado ninguna versión; inténtalo más tarde.',
    generation_failed: 'No hemos conseguido un texto que cumpla nuestras reglas (sin datos inventados). No se ha gastado ninguna versión; inténtalo de nuevo.',
    premium_required: 'Preparar contenido está incluido en la prueba gratuita y en la suscripción.',
    rate_limited: 'Has hecho muchas solicitudes seguidas. Inténtalo dentro de un rato.',
    unauthorized: 'Tu sesión ha caducado. Vuelve a iniciar sesión.',
    invalid_week: 'Ha empezado una semana nueva. Recarga la página para preparar el contenido de esta semana.',
    unavailable: 'No hemos podido preparar tu contenido. No se ha gastado ninguna versión; inténtalo de nuevo.',
    load_failed: 'No hemos podido cargar tu contenido de la semana.',
  } satisfies Record<WeeklyContentErrorCode, string>,
  report: {
    title: 'Tu contenido de la semana',
    note: 'Preparar, editar o copiar un borrador no significa que se haya publicado. No medimos su efecto en visitas, clientes ni posicionamiento.',
    prepared: 'Contenido preparado', edited: 'Editado por ti', copied: 'Copiado',
    versions: (n: number) => (n === 1 ? '1 versión' : `${n} versiones`),
    yes: 'Sí', no: 'No',
    none: 'Aún no has preparado el contenido de esta semana.', go: 'Ir a Hoy',
    error: 'No hemos podido cargar el estado de tu contenido semanal.',
  },
};

type Copy = typeof ES;

const EN: Copy = {
  title: 'Your content of the week',
  intro: 'Each week we help you prepare a post to give your business visibility.',
  week: (from, to) => `Week of ${from} to ${to}`,
  draft: 'Draft · not published',
  prepare: 'Prepare my content',
  preparing: 'Preparing your content...',
  prepareNote: 'We only use your business details. We never make up prices, offers, opening hours or reviews.',
  copy: 'Copy', copied: 'Copied', edit: 'Edit', another: 'Another version',
  remaining: (n) => `${n} left`,
  save: 'Save changes', saving: 'Saving...', cancel: 'Cancel',
  saved: 'Saved', editedSaved: 'Edited by you · saved', copiedOnce: 'Copied to clipboard',
  unsaved: 'Unsaved changes',
  limitInfo: "You've used this week's 3 versions. You can keep editing this text.",
  replaceEdited: 'Your edited text will be replaced by a new version. Continue?',
  replaceYes: 'Yes, create another version', replaceNo: 'No, keep my text',
  chars: (n, max) => `${n}/${max}`,
  emptyEdit: 'The text cannot be empty.',
  tooLong: 'The text is too long.',
  incompleteTitle: 'Complete your business to prepare your content',
  incompleteText: 'We need the name, activity, city and at least one service, so the text is truly about your business and not generic.',
  incompleteCta: 'Complete my business',
  lockedText: 'Preparing content is included in the free trial and the subscription.',
  loadError: "We couldn't load your content of the week.",
  retry: 'Retry',
  saveError: "We couldn't save your changes. Your text is still here; please try again.",
  conflict: 'This content changed in another window. Copy your text if you want to keep it, then load the latest version.',
  loadLatest: 'Load the latest version',
  copyError: "We couldn't copy the text. Select it and copy it manually.",
  close: 'Close',
  editLabel: 'Your post text',
  errors: {
    profile_incomplete: 'Some business details are missing to prepare accurate content. Complete them in My business.',
    limit_reached: "You've used this week's 3 versions. You can keep editing the current text.",
    in_progress: "We're already preparing your content in another window. Wait a few seconds and try again.",
    ai_unavailable: "The writing service isn't available right now. No version was used; please try later.",
    generation_failed: "We couldn't get a text that follows our rules (no made-up details). No version was used; please try again.",
    premium_required: 'Preparing content is included in the free trial and the subscription.',
    rate_limited: "You've made many requests in a row. Please try again in a while.",
    unauthorized: 'Your session has expired. Please sign in again.',
    invalid_week: 'A new week has started. Reload the page to prepare this week\u2019s content.',
    unavailable: "We couldn't prepare your content. No version was used; please try again.",
    load_failed: "We couldn't load your content of the week.",
  },
  report: {
    title: 'Your content of the week',
    note: 'Preparing, editing or copying a draft does not mean it was published. We do not measure its effect on visits, customers or rankings.',
    prepared: 'Content prepared', edited: 'Edited by you', copied: 'Copied',
    versions: (n) => (n === 1 ? '1 version' : `${n} versions`),
    yes: 'Yes', no: 'No',
    none: "You haven't prepared this week's content yet.", go: 'Go to Today',
    error: "We couldn't load the status of your weekly content.",
  },
};

export const WEEKLY_COPY = { es: ES, en: EN };
export type WeeklyCopy = Copy;
