/*
# v0.7.2 - "Mejora tu negocio en 2 minutos" (business improvement drafts)

Stores one editable, AI-prepared text per business and per compatible recommendation,
plus a per-user monthly usage counter that caps AI spending across all businesses.
A prepared text is only a draft: nothing here means it was applied or published,
and nothing here changes the status of the recommendation.

1. New Tables
- `business_improvement_drafts`
  - `id` (uuid, primary key)
  - `user_id` (uuid, owner, defaults to the signed-in user)
  - `business_id` (uuid, business the draft belongs to)
  - `semantic_key` (text, stable key of the recommendation: its rule id, plus the
    service for service descriptions). If the action engine recreates the same
    recommendation with a new id, the draft and its counters are kept.
  - `kind` (text: business_description | service_description | faq)
  - `mode` (text: create | improve; improve = rewrite of a text the owner provided)
  - `action_id` (uuid, last recommendation that used this draft, informative only)
  - `lang` (text, 'es' or 'en')
  - `content` (text, current editable text, max 2000 chars)
  - `source_text` (text, original text provided by the owner for "improve", max 1500)
  - `versions` (jsonb array, every text generated by the AI, max 3) so earlier
    versions stay viewable
  - `generations` (0..3 successful versions), `attempts` (0..6 generation requests)
  - `generating_since`, `reservation_id` (generation lock and its unique token)
  - `generated_at`, `edited_at`, `copied_at`, `created_at`, `updated_at`
  - Unique per (business_id, semantic_key): several tabs can never create duplicates.
- `business_improvement_usage`
  - `user_id`, `period_start` (first day of the UTC month), `requests` (0..40)
  - Global monthly cap of 40 generation requests per user for this feature,
    whatever the number of businesses or recommendations.

2. Security
- RLS enabled on both tables.
- Drafts: owners may SELECT and UPDATE only their own drafts of businesses they own.
  No INSERT/DELETE policy: rows are created only by the server function.
  Column privileges: the browser may update only `content` and `copied_at`, and cannot
  read `reservation_id`.
- Usage: owners may only SELECT their own counters; no browser writes.
- reserve / complete / release are SECURITY DEFINER and executable only by
  `service_role` (the `business-improvement` edge function, after verifying the user
  and Premium access). Browser roles cannot call them.

3. Important notes
1. Incremental and idempotent; no existing table, action or billing data is modified.
2. Limits are enforced atomically in the database under row locks: 3 versions and
   6 attempts per recommendation, 40 requests per user per month.
3. An attempt is consumed only when generation actually starts. Validation errors,
   missing Premium, busy/stale/limit answers and the global cap consume nothing.
4. Every reservation gets a fresh token; complete/release require it, so an old
   request can never finish, count or release a newer reservation. A lock expires
   after 90 seconds so an interrupted request can be recovered.
*/

CREATE TABLE IF NOT EXISTS public.business_improvement_drafts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  business_id uuid NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
  semantic_key text NOT NULL,
  kind text NOT NULL,
  mode text NOT NULL DEFAULT 'create',
  action_id uuid REFERENCES public.business_actions(id) ON DELETE SET NULL,
  lang text NOT NULL DEFAULT 'es',
  content text NOT NULL DEFAULT '',
  source_text text NOT NULL DEFAULT '',
  versions jsonb NOT NULL DEFAULT '[]'::jsonb,
  generations smallint NOT NULL DEFAULT 0,
  attempts smallint NOT NULL DEFAULT 0,
  generating_since timestamptz,
  reservation_id uuid,
  generated_at timestamptz,
  edited_at timestamptz,
  copied_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT business_improvement_drafts_business_key UNIQUE (business_id, semantic_key),
  CONSTRAINT business_improvement_drafts_key_len CHECK (char_length(semantic_key) BETWEEN 1 AND 160),
  CONSTRAINT business_improvement_drafts_kind_check CHECK (kind IN ('business_description', 'service_description', 'faq')),
  CONSTRAINT business_improvement_drafts_mode_check CHECK (mode IN ('create', 'improve')),
  CONSTRAINT business_improvement_drafts_lang_check CHECK (lang IN ('es', 'en')),
  CONSTRAINT business_improvement_drafts_content_len CHECK (char_length(content) <= 2000),
  CONSTRAINT business_improvement_drafts_source_len CHECK (char_length(source_text) <= 1500),
  CONSTRAINT business_improvement_drafts_versions_shape CHECK (jsonb_typeof(versions) = 'array' AND jsonb_array_length(versions) <= 3),
  CONSTRAINT business_improvement_drafts_generations_range CHECK (generations BETWEEN 0 AND 3),
  CONSTRAINT business_improvement_drafts_attempts_range CHECK (attempts BETWEEN 0 AND 6),
  CONSTRAINT business_improvement_drafts_generations_le_attempts CHECK (generations <= attempts),
  CONSTRAINT business_improvement_drafts_content_present CHECK (
    (generations = 0 AND content = '') OR (generations > 0 AND char_length(btrim(content)) > 0)
  )
);

CREATE INDEX IF NOT EXISTS business_improvement_drafts_user_business_idx
  ON public.business_improvement_drafts (user_id, business_id);
CREATE INDEX IF NOT EXISTS business_improvement_drafts_action_idx
  ON public.business_improvement_drafts (action_id);

CREATE TABLE IF NOT EXISTS public.business_improvement_usage (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  period_start date NOT NULL,
  requests integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, period_start),
  CONSTRAINT business_improvement_usage_requests_range CHECK (requests BETWEEN 0 AND 40),
  CONSTRAINT business_improvement_usage_period_is_month CHECK (extract(day FROM period_start) = 1)
);

ALTER TABLE public.business_improvement_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_improvement_usage ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.business_improvement_drafts FROM anon;
REVOKE ALL ON public.business_improvement_drafts FROM authenticated;
GRANT SELECT (
  id, user_id, business_id, semantic_key, kind, mode, action_id, lang, content, source_text, versions,
  generations, attempts, generating_since, generated_at, edited_at, copied_at, created_at, updated_at
) ON public.business_improvement_drafts TO authenticated;
GRANT UPDATE (content, copied_at) ON public.business_improvement_drafts TO authenticated;

REVOKE ALL ON public.business_improvement_usage FROM anon;
REVOKE ALL ON public.business_improvement_usage FROM authenticated;
GRANT SELECT ON public.business_improvement_usage TO authenticated;

DROP POLICY IF EXISTS "select_own_business_improvements" ON public.business_improvement_drafts;
CREATE POLICY "select_own_business_improvements" ON public.business_improvement_drafts FOR SELECT
  TO authenticated
  USING (
    auth.uid() = user_id
    AND EXISTS (SELECT 1 FROM public.businesses b WHERE b.id = business_id AND b.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "update_own_business_improvements" ON public.business_improvement_drafts;
CREATE POLICY "update_own_business_improvements" ON public.business_improvement_drafts FOR UPDATE
  TO authenticated
  USING (
    auth.uid() = user_id
    AND EXISTS (SELECT 1 FROM public.businesses b WHERE b.id = business_id AND b.user_id = auth.uid())
  )
  WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (SELECT 1 FROM public.businesses b WHERE b.id = business_id AND b.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "select_own_business_improvement_usage" ON public.business_improvement_usage;
CREATE POLICY "select_own_business_improvement_usage" ON public.business_improvement_usage FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.business_improvement_drafts_before_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.generations = OLD.generations AND NEW.content IS DISTINCT FROM OLD.content THEN
    NEW.edited_at := now();
  END IF;
  IF NEW.copied_at IS NOT NULL AND NEW.copied_at IS DISTINCT FROM OLD.copied_at THEN
    NEW.copied_at := now();
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS business_improvement_drafts_before_update ON public.business_improvement_drafts;
CREATE TRIGGER business_improvement_drafts_before_update
  BEFORE UPDATE ON public.business_improvement_drafts
  FOR EACH ROW EXECUTE FUNCTION public.business_improvement_drafts_before_update();

CREATE OR REPLACE FUNCTION public.reserve_business_improvement(
  p_user_id uuid, p_business_id uuid, p_action_id uuid, p_semantic_key text, p_kind text, p_expected_generations integer
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.business_improvement_drafts;
  v_action public.business_actions;
  v_token uuid := gen_random_uuid();
  v_period date := date_trunc('month', timezone('utc', now()))::date;
  v_used integer;
BEGIN
  IF p_user_id IS NULL OR p_business_id IS NULL OR p_action_id IS NULL OR p_semantic_key IS NULL
     OR char_length(p_semantic_key) NOT BETWEEN 1 AND 160
     OR p_kind NOT IN ('business_description', 'service_description', 'faq') THEN
    RETURN jsonb_build_object('status', 'invalid');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.businesses WHERE id = p_business_id AND user_id = p_user_id) THEN
    RETURN jsonb_build_object('status', 'not_found');
  END IF;

  SELECT * INTO v_action FROM public.business_actions
  WHERE id = p_action_id AND user_id = p_user_id AND business_id = p_business_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('status', 'not_found');
  END IF;
  IF p_semantic_key <> v_action.rule_id AND p_semantic_key NOT LIKE v_action.rule_id || ':%' THEN
    RETURN jsonb_build_object('status', 'invalid');
  END IF;
  IF v_action.status NOT IN ('PENDING', 'IN_PROGRESS') THEN
    RETURN jsonb_build_object('status', 'closed');
  END IF;

  INSERT INTO public.business_improvement_drafts (user_id, business_id, semantic_key, kind, action_id)
  VALUES (p_user_id, p_business_id, p_semantic_key, p_kind, p_action_id)
  ON CONFLICT (business_id, semantic_key) DO NOTHING;

  SELECT * INTO v_row FROM public.business_improvement_drafts
  WHERE business_id = p_business_id AND semantic_key = p_semantic_key
  FOR UPDATE;

  IF v_row.user_id <> p_user_id THEN
    RETURN jsonb_build_object('status', 'not_found');
  END IF;
  IF p_expected_generations IS DISTINCT FROM v_row.generations THEN
    RETURN jsonb_build_object('status', 'stale', 'generations', v_row.generations);
  END IF;
  IF v_row.generations >= 3 THEN
    RETURN jsonb_build_object('status', 'limit', 'generations', v_row.generations);
  END IF;
  IF v_row.generating_since IS NOT NULL AND v_row.generating_since > now() - interval '90 seconds' THEN
    RETURN jsonb_build_object('status', 'busy', 'generations', v_row.generations);
  END IF;
  IF v_row.attempts >= 6 THEN
    RETURN jsonb_build_object('status', 'attempts', 'generations', v_row.generations, 'attempts', v_row.attempts);
  END IF;

  INSERT INTO public.business_improvement_usage AS u (user_id, period_start, requests)
  VALUES (p_user_id, v_period, 1)
  ON CONFLICT (user_id, period_start)
  DO UPDATE SET requests = u.requests + 1, updated_at = now()
  WHERE u.requests < 40
  RETURNING u.requests INTO v_used;

  IF v_used IS NULL THEN
    RETURN jsonb_build_object('status', 'global', 'generations', v_row.generations);
  END IF;

  UPDATE public.business_improvement_drafts
  SET generating_since = now(), reservation_id = v_token, attempts = attempts + 1, action_id = p_action_id
  WHERE id = v_row.id;

  RETURN jsonb_build_object(
    'status', 'reserved', 'id', v_row.id, 'reservation', v_token,
    'generations', v_row.generations, 'attempts', v_row.attempts + 1, 'global_used', v_used
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_business_improvement(
  p_id uuid, p_user_id uuid, p_reservation_id uuid, p_content text, p_lang text, p_mode text, p_source_text text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id uuid;
BEGIN
  IF p_reservation_id IS NULL OR p_content IS NULL OR char_length(btrim(p_content)) = 0
     OR char_length(p_content) > 2000 OR p_lang NOT IN ('es', 'en') OR p_mode NOT IN ('create', 'improve')
     OR char_length(coalesce(p_source_text, '')) > 1500 THEN
    RETURN false;
  END IF;
  UPDATE public.business_improvement_drafts
  SET content = p_content, versions = versions || jsonb_build_array(p_content), lang = p_lang,
      mode = p_mode, source_text = coalesce(p_source_text, ''),
      generations = generations + 1, generating_since = NULL, reservation_id = NULL,
      generated_at = now(), edited_at = NULL, copied_at = NULL
  WHERE id = p_id AND user_id = p_user_id AND reservation_id = p_reservation_id
    AND generating_since IS NOT NULL AND generations < 3
  RETURNING id INTO v_id;
  RETURN v_id IS NOT NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.release_business_improvement(p_id uuid, p_user_id uuid, p_reservation_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id uuid;
BEGIN
  IF p_reservation_id IS NULL THEN
    RETURN false;
  END IF;
  UPDATE public.business_improvement_drafts SET generating_since = NULL, reservation_id = NULL
  WHERE id = p_id AND user_id = p_user_id AND reservation_id = p_reservation_id
  RETURNING id INTO v_id;
  RETURN v_id IS NOT NULL;
END;
$$;

REVOKE ALL ON FUNCTION public.reserve_business_improvement(uuid, uuid, uuid, text, text, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_business_improvement(uuid, uuid, uuid, text, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.release_business_improvement(uuid, uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.business_improvement_drafts_before_update() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_business_improvement(uuid, uuid, uuid, text, text, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_business_improvement(uuid, uuid, uuid, text, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.release_business_improvement(uuid, uuid, uuid) TO service_role;
