import type { ImprovementErrorCode, ImprovementKind, ProfileField } from './model';

export type PanelState =
  | 'empty' | 'preparing' | 'available' | 'editing' | 'saving' | 'saved' | 'error'
  | 'limit' | 'incomplete' | 'locked';

const ES = {
  title: 'Te ayudamos a prepararlo en 2 minutos',
  intro: {
    business_description: 'Preparamos una propuesta de descripción de tu negocio con los datos que nos diste. Tú la revisas, la editas y la copias donde quieras usarla.',
    service_description: 'Preparamos una propuesta de descripción de este servicio con los datos que nos diste. Tú la revisas, la editas y la copias.',
    faq: 'Preparamos unas preguntas frecuentes para tu web con lo que sabemos de tu negocio. Revísalas antes de usarlas.',
  } satisfies Record<ImprovementKind, string>,
  service: (s: string) => `Servicio: ${s}`,
  states: {
    empty: 'Sin preparar', preparing: 'Preparando', available: 'Disponible', editing: 'Editando', saving: 'Guardando',
    saved: 'Guardado', error: 'Error', limit: 'Límite alcanzado', incomplete: 'Perfil incompleto', locked: 'Sin suscripción',
  } satisfies Record<PanelState, string>,
  stateLabel: 'Estado',
  pending: 'Texto preparado · pendiente de aplicar',
  basedOn: 'Basado solo en lo que declaraste en tu perfil:',
  fields: { name: 'nombre', category: 'actividad', city: 'ciudad', services: 'servicios', audience: 'público', source: 'tu texto original' },
  generalNote: 'Es una recomendación general de buenas prácticas, no un problema que hayamos detectado en tu negocio.',
  modeLabel: '¿Qué quieres hacer?',
  modeCreate: 'Crear una propuesta nueva',
  modeImprove: 'Mejorar un texto que ya tengo',
  sourceLabel: 'Pega aquí tu texto actual',
  sourceHint: (min: number, max: number) => `Entre ${min} y ${max} caracteres. Lo dejaremos más claro sin añadir datos nuevos.`,
  sourceShort: (min: number) => `Pega al menos ${min} caracteres de tu texto.`,
  sourceLong: 'El texto es demasiado largo.',
  prepare: 'Preparar mi mejora',
  preparing: 'Preparando tu texto...',
  prepareNote: 'Usamos solo los datos de tu negocio. No inventamos precios, ofertas, horarios, opiniones ni resultados.',
  copy: 'Copiar', copied: 'Copiado', edit: 'Editar', another: 'Otra versión',
  remaining: (n: number) => (n === 1 ? 'queda 1' : `quedan ${n}`),
  save: 'Guardar cambios', saving: 'Guardando...', cancel: 'Cancelar',
  saved: 'Guardado', editedSaved: 'Editado por ti · guardado',
  copiedNote: 'Copiado. Copiar no publica ni aplica el texto: la acción sigue pendiente hasta que la completes como siempre.',
  unsaved: 'Cambios sin guardar',
  versions: (n: number) => `Versiones preparadas (${n})`,
  versionN: (n: number) => `Versión ${n}`,
  useVersion: 'Usar esta versión',
  current: 'En uso',
  limitInfo: 'Has usado las 3 versiones de esta mejora. Puedes seguir editando el texto.',
  attemptsInfo: 'Has agotado los intentos de esta mejora. Puedes seguir editando el texto.',
  attemptsNoDraft: 'No hemos podido preparar este texto tras varios intentos. Puedes completar la acción por tu cuenta.',
  usage: (n: number, max: number) => `Este mes has usado ${n} de ${max} preparaciones.`,
  replaceEdited: 'Has editado este texto. Si preparas otra versión, sustituirá a tu edición (las versiones anteriores siguen guardadas). ¿Continuar?',
  replaceYes: 'Sí, preparar otra versión', replaceNo: 'No, mantener mi texto',
  chars: (n: number, max: number) => `${n}/${max}`,
  emptyEdit: 'El texto no puede quedar vacío.',
  tooLong: 'El texto es demasiado largo.',
  incompleteTitle: 'Completa tu negocio para preparar este texto',
  incompleteText: (fields: string) => `Nos falta: ${fields}. Así el texto habla de tu negocio de verdad. También puedes pegar un texto que ya tengas para mejorarlo.`,
  incompleteCta: 'Completar mi negocio',
  serviceGone: 'Este servicio ya no está en tu lista de servicios. Añádelo en Mi negocio si quieres preparar su descripción.',
  lockedText: 'Preparar mejoras está incluido en la prueba gratuita y en la suscripción.',
  loadError: 'No hemos podido cargar tu texto preparado.',
  retry: 'Reintentar',
  saveError: 'No hemos podido guardar tus cambios. Tu texto sigue aquí; inténtalo de nuevo.',
  conflict: 'Este texto ha cambiado en otra ventana. Copia tu texto si quieres conservarlo y carga la última versión.',
  loadLatest: 'Cargar la última versión',
  copyError: 'No hemos podido copiar el texto. Selecciónalo y cópialo manualmente.',
  close: 'Cerrar',
  editLabel: 'Texto preparado',
  hint: 'Te ayudamos a prepararlo en 2 minutos',
  errors: {
    profile_incomplete: 'Faltan datos de tu negocio para preparar un texto fiel. Complétalos en Mi negocio.',
    service_not_declared: 'Este servicio ya no está en tu lista de servicios. Añádelo en Mi negocio para preparar su descripción.',
    incompatible_action: 'Esta recomendación no admite preparar un texto.',
    action_closed: 'Esta recomendación ya está cerrada. Tu texto preparado sigue disponible.',
    edited_conflict: 'Has editado este texto en otra ventana. Confirma si quieres sustituirlo por una versión nueva.',
    limit_reached: 'Ya has usado las 3 versiones de esta mejora. Puedes seguir editando el texto actual.',
    attempts_exhausted: 'Has agotado los intentos de preparación de esta mejora.',
    global_limit: 'Has alcanzado el máximo de preparaciones de este mes. Podrás preparar más el mes que viene; tus textos guardados siguen disponibles.',
    monthly_limit: 'Has alcanzado el límite de uso de esta función. Podrás usarla de nuevo el mes que viene; tus textos guardados siguen disponibles.',
    in_progress: 'Ya estamos preparando este texto en otra ventana. Espera unos segundos y vuelve a intentarlo.',
    ai_unavailable: 'El servicio de redacción no está disponible ahora mismo. No se ha gastado ninguna versión; inténtalo más tarde.',
    generation_failed: 'No hemos conseguido un texto que cumpla nuestras reglas (sin datos inventados). No se ha gastado ninguna versión; inténtalo de nuevo.',
    premium_required: 'Preparar mejoras está incluido en la prueba gratuita y en la suscripción.',
    rate_limited: 'Has hecho muchas solicitudes seguidas. Inténtalo dentro de un rato.',
    unauthorized: 'Tu sesión ha caducado. Vuelve a iniciar sesión.',
    invalid_request: 'Revisa el texto que has pegado e inténtalo de nuevo.',
    not_found: 'No encontramos esta recomendación para tu negocio. Recarga la página.',
    unavailable: 'No hemos podido preparar tu texto. Inténtalo de nuevo.',
    load_failed: 'No hemos podido cargar tu texto preparado.',
  } satisfies Record<ImprovementErrorCode, string>,
};

type Copy = typeof ES;

const EN: Copy = {
  title: 'We help you prepare it in 2 minutes',
  intro: {
    business_description: 'We prepare a proposed description of your business using the details you gave us. You review it, edit it and copy it wherever you want to use it.',
    service_description: 'We prepare a proposed description of this service using the details you gave us. You review it, edit it and copy it.',
    faq: 'We prepare some frequently asked questions for your website with what we know about your business. Review them before using them.',
  },
  service: (s) => `Service: ${s}`,
  states: {
    empty: 'Not prepared', preparing: 'Preparing', available: 'Available', editing: 'Editing', saving: 'Saving',
    saved: 'Saved', error: 'Error', limit: 'Limit reached', incomplete: 'Profile incomplete', locked: 'No subscription',
  },
  stateLabel: 'Status',
  pending: 'Text prepared · not applied yet',
  basedOn: 'Based only on what you declared in your profile:',
  fields: { name: 'name', category: 'activity', city: 'city', services: 'services', audience: 'audience', source: 'your original text' },
  generalNote: 'This is a general best-practice recommendation, not a problem we detected in your business.',
  modeLabel: 'What would you like to do?',
  modeCreate: 'Create a new proposal',
  modeImprove: 'Improve a text I already have',
  sourceLabel: 'Paste your current text here',
  sourceHint: (min, max) => `Between ${min} and ${max} characters. We will make it clearer without adding new details.`,
  sourceShort: (min) => `Paste at least ${min} characters of your text.`,
  sourceLong: 'The text is too long.',
  prepare: 'Prepare my improvement',
  preparing: 'Preparing your text...',
  prepareNote: 'We only use your business details. We never make up prices, offers, opening hours, reviews or results.',
  copy: 'Copy', copied: 'Copied', edit: 'Edit', another: 'Another version',
  remaining: (n) => `${n} left`,
  save: 'Save changes', saving: 'Saving...', cancel: 'Cancel',
  saved: 'Saved', editedSaved: 'Edited by you · saved',
  copiedNote: 'Copied. Copying does not publish or apply the text: the action stays pending until you complete it as usual.',
  unsaved: 'Unsaved changes',
  versions: (n) => `Prepared versions (${n})`,
  versionN: (n) => `Version ${n}`,
  useVersion: 'Use this version',
  current: 'In use',
  limitInfo: "You've used the 3 versions of this improvement. You can keep editing the text.",
  attemptsInfo: "You've used all attempts for this improvement. You can keep editing the text.",
  attemptsNoDraft: "We couldn't prepare this text after several attempts. You can complete the action on your own.",
  usage: (n, max) => `This month you have used ${n} of ${max} preparations.`,
  replaceEdited: 'You edited this text. If you prepare another version it will replace your edit (earlier versions stay saved). Continue?',
  replaceYes: 'Yes, prepare another version', replaceNo: 'No, keep my text',
  chars: (n, max) => `${n}/${max}`,
  emptyEdit: 'The text cannot be empty.',
  tooLong: 'The text is too long.',
  incompleteTitle: 'Complete your business to prepare this text',
  incompleteText: (fields) => `Missing: ${fields}. This way the text is truly about your business. You can also paste a text you already have to improve it.`,
  incompleteCta: 'Complete my business',
  serviceGone: 'This service is no longer in your services list. Add it in My business if you want to prepare its description.',
  lockedText: 'Preparing improvements is included in the free trial and the subscription.',
  loadError: "We couldn't load your prepared text.",
  retry: 'Retry',
  saveError: "We couldn't save your changes. Your text is still here; please try again.",
  conflict: 'This text changed in another window. Copy your text if you want to keep it, then load the latest version.',
  loadLatest: 'Load the latest version',
  copyError: "We couldn't copy the text. Select it and copy it manually.",
  close: 'Close',
  editLabel: 'Prepared text',
  hint: 'We help you prepare it in 2 minutes',
  errors: {
    profile_incomplete: 'Some business details are missing to prepare an accurate text. Complete them in My business.',
    service_not_declared: 'This service is no longer in your services list. Add it in My business to prepare its description.',
    incompatible_action: 'This recommendation does not support preparing a text.',
    action_closed: 'This recommendation is already closed. Your prepared text is still available.',
    edited_conflict: 'You edited this text in another window. Confirm whether you want to replace it with a new version.',
    limit_reached: "You've used the 3 versions of this improvement. You can keep editing the current text.",
    attempts_exhausted: "You've used all preparation attempts for this improvement.",
    global_limit: "You've reached this month's maximum number of preparations. You can prepare more next month; your saved texts remain available.",
    monthly_limit: "You've reached the usage limit for this feature. You can use it again next month; your saved texts remain available.",
    in_progress: "We're already preparing this text in another window. Wait a few seconds and try again.",
    ai_unavailable: "The writing service isn't available right now. No version was used; please try later.",
    generation_failed: "We couldn't get a text that follows our rules (no made-up details). No version was used; please try again.",
    premium_required: 'Preparing improvements is included in the free trial and the subscription.',
    rate_limited: "You've made many requests in a row. Please try again in a while.",
    unauthorized: 'Your session has expired. Please sign in again.',
    invalid_request: 'Check the text you pasted and try again.',
    not_found: "We couldn't find this recommendation for your business. Reload the page.",
    unavailable: "We couldn't prepare your text. Please try again.",
    load_failed: "We couldn't load your prepared text.",
  },
};

export const IMPROVEMENT_COPY = { es: ES, en: EN };
export type ImprovementCopy = Copy;
export type FieldKey = ProfileField;
